language: python

python:
  - "3.6"

cache:
  apt: true
  directories:
    - $HOME/miniconda

# See http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
services:
  - xvfb

install:
  # install miniconda for Python dependencies
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda info -a
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest libgfortran pysam htseq pybedtools bedtools palettable pybigwig coverage coveralls python-coveralls scikit-learn

    # # command to run tests, e.g. python setup.py test
script:
  - coverage run setup.py test

after_sucess:
  - coveralls
